name: SoulCare Cronjob

on:
  schedule:
    - cron: '*/1 * * * *' # jede Minute
  workflow_dispatch:       # zum manuellen Ausführen

jobs:
  ping-vercel-api:
    runs-on: ubuntu-latest
    steps:
      - name: Request to scheduledSend
        run: curl -s https://soulcare-mu.vercel.app/api/scheduledSend
