name: Cron E-Mail Scheduler

on:
  schedule:
    - cron: '*/1 * * * *' # jede Minute
  workflow_dispatch:      # manuelles Auslösen über GitHub

jobs:
  trigger-vercel-api:
    runs-on: ubuntu-latest
    steps:
      - name: Anfrage an Vercel-API senden
        run: curl -s -o /dev/null -w "%{http_code}" https://soulcare-mu.vercel.app/api/scheduledSend
