name: Schedule Send Emails

on:
  schedule:
    - cron: '*/1 * * * *'  # Alle 1 Minute

jobs:
  send_emails:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Vercel API
      run: |
        curl -X GET https://soulcare-mu.vercel.app/api/sendNotifications  # Ersetze mit deiner tatsächlichen URL
